### ISSUE TITLE
iam_policy.json does not validate, missing "Version" info

### ISSUE THREAD

**Issue by rayjanwilson** [awslabs/eb-node-express-signup#2]
Following the [Deploying a Web Application Guide](http://docs.aws.amazon.com/gettingstarted/latest/deploy/setting-up.html), we are asked to use this repo. The provided iam_policy.json does not validate (Step 7), responding that a valid IAM policy requires a Version. 

[Example policies](http://docs.aws.amazon.com/IAM/latest/UserGuide/ExampleIAMPolicies.html) show how to add the Version. 

Below is a proposed valid iam_policy.json. Hope this is helpful.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "sns:Publish"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by bekroogle** [comment]
Maybe you should issue a pull request. I went through the same thing, but ended up hacking at it trial/error style until I got it to validate.

**Comment by butl4701** [comment]
Please do issue a pull request. I tried hacking for nearly an hour before I realized that you had posted this new version. Thank you for this. Good stuff and allowed me to continue working through the tut.

**Comment by rayjanwilson** [comment]
AndrewCh submitted the pull request [here](https://github.com/awslabs/eb-node-express-signup/pull/3). Cheers.

**Comment by huntsper** [comment]
Thanks much!

**Comment by Ben-Butler** [comment]
yes, thanks **Rayjanwilson** very uch appreciated.

**Comment by bekroogle** [comment]
:clap:
